name: dev.mnist.env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - azure-cli
      - azure-identity
      - azure-storage-blob
      - gunicorn
      - joblib
      - matplotlib
      - mlflow
      - numpy
      - pandas
      - pyyaml
      - requests
      - scikit-learn
      - scipy
      - urllib3
      - uvicorn
      - xgboost
