# Your workflow name.
name: Deploy to DockerHub

# Run workflow on every push to master branch.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [ main ]
  #   pull_request:
  #     branches: [ main ]
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build . -t ggndp/mnistclassifier:${{ github.sha }}
          docker push ggndp/mnistclassifier:${{ github.sha }}
